# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_gallery.models.Gallery


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='title slug')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('original_file', models.ImageField(upload_to=django_gallery.models.Gallery.get_storage_path, verbose_name='image')),
                ('thumbnail', models.ImageField(upload_to=django_gallery.models.Gallery.get_storage_path)),
                ('large_thumbnail', models.ImageField(upload_to=django_gallery.models.Gallery.get_storage_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_gallery.Gallery', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='django_gallery.Image', verbose_name='gallery image'),
        ),
    ]
