# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'permissions': (('view_gallery', 'Can view gallery'),), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
