# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0002_auto_20160217_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('view_gallery', 'Can view gallery'),), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'permissions': (('view_image', 'Can view image'),), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
