# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 16:13
from __future__ import unicode_literals

from django.db import migrations
import django_gallery.models.gallery
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0002_auto_20160229_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(editable=False, upload_to=django_gallery.models.gallery.get_storage_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(editable=False, upload_to=django_gallery.models.gallery.get_storage_path),
        ),
    ]
