# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0003_auto_20160217_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_gallery.Gallery', verbose_name='gallery'),
        ),
    ]
