# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0003_auto_20160229_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='large_thumbnail',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
