# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gallery', '0004_auto_20160217_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='django_gallery.Image', verbose_name='gallery image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_gallery.Gallery', verbose_name='gallery'),
        ),
    ]
